<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="template\Helper\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.Api.Db\Template.Api.Db.csproj" />
    <ProjectReference Include="..\Template.Api.Dto\Template.Api.Dto.csproj" />
    <ProjectReference Include="..\Template.Api.Model\Template.Api.Model.csproj" />
  </ItemGroup>

</Project>
